grid_map_topic: /elevation_map_modified

grid_map_visualizations:

  - name: elevation_grid
    type: occupancy_grid
    params:
      layer: elevation_fused
      data_min: -0.05 ##-0.05
      data_max: -0.06 #-0.08

  #- name: elevation_grid_high
  #  type: occupancy_grid
  #  params:
  #    layer: elevation
  #    data_min: 0.05 ##-0.05
  #    data_max: 0.06 #-0.08




    



